name: pottr_env
channels:
  - conda-forge
  - gurobi
dependencies:
  - python = 3.12.12
  - pandas = 3.0.1
  - networkx = 3.6.1
  - gurobi = 13.0.1
  - pydot = 4.0.1
  - altair = 6.0.0
  - scipy = 1.17.1
  - filelock = 3.16.1
  - pyreadr = 0.5.4
  - openpyxl = 3.1.5